// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MLP_MLP,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.288000,HLS_SYN_LAT=207259,HLS_SYN_TPT=none,HLS_SYN_MEM=167,HLS_SYN_DSP=0,HLS_SYN_FF=34451,HLS_SYN_LUT=29276,HLS_VERSION=2024_1}" *)

module MLP (
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [3:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [4:0] INPUT_STREAM_TID;
input  [4:0] INPUT_STREAM_TDEST;
output  [31:0] OUTPUT_STREAM_TDATA;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output  [3:0] OUTPUT_STREAM_TKEEP;
output  [3:0] OUTPUT_STREAM_TSTRB;
output  [3:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [4:0] OUTPUT_STREAM_TID;
output  [4:0] OUTPUT_STREAM_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [9:0] image_pixels_address0;
reg    image_pixels_ce0;
reg    image_pixels_we0;
wire   [31:0] image_pixels_q0;
reg   [6:0] l_hidden2_outputs_address0;
reg    l_hidden2_outputs_ce0;
reg    l_hidden2_outputs_we0;
wire   [31:0] l_hidden2_outputs_q0;
reg   [3:0] l_out_outputs_address0;
reg    l_out_outputs_ce0;
reg    l_out_outputs_we0;
wire   [31:0] l_out_outputs_q0;
reg    l_out_outputs_ce1;
wire   [31:0] l_out_outputs_q1;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_done;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_idle;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_ready;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_INPUT_STREAM_TREADY;
wire   [9:0] grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_address0;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_ce0;
wire    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_we0;
wire   [31:0] grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_d0;
wire    grp_MLP_Pipeline_L1_L2_fu_507_ap_start;
wire    grp_MLP_Pipeline_L1_L2_fu_507_ap_done;
wire    grp_MLP_Pipeline_L1_L2_fu_507_ap_idle;
wire    grp_MLP_Pipeline_L1_L2_fu_507_ap_ready;
wire   [9:0] grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_address0;
wire    grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_ce0;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out1;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out1_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out2;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out2_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out3;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out3_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out4;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out4_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out5;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out5_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out6;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out6_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out7;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out7_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out8;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out8_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out9;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out9_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out10;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out10_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out11;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out11_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out12;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out12_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out13;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out13_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out14;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out14_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out15;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out15_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out16;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out16_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out17;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out17_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out18;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out18_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out19;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out19_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out20;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out20_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out21;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out21_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out22;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out22_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out23;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out23_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out24;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out24_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out25;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out25_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out26;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out26_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out27;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out27_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out28;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out28_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out29;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out29_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out30;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out30_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out31;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out31_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out32;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out32_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out33;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out33_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out34;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out34_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out35;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out35_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out36;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out36_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out37;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out37_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out38;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out38_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out39;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out39_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out40;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out40_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out41;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out41_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out42;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out42_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out43;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out43_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out44;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out44_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out45;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out45_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out46;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out46_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out47;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out47_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out48;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out48_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out49;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out49_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out50;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out50_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out51;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out51_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out52;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out52_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out53;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out53_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out54;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out54_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out55;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out55_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out56;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out56_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out57;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out57_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out58;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out58_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out59;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out59_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out60;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out60_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out61;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out61_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out62;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out62_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_p_out63;
wire    grp_MLP_Pipeline_L1_L2_fu_507_p_out63_ap_vld;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_opcode;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din1;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_din0;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_din0;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din1;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_opcode;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din1;
wire    grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_ce;
wire    grp_MLP_Pipeline_L1_fu_580_ap_start;
wire    grp_MLP_Pipeline_L1_fu_580_ap_done;
wire    grp_MLP_Pipeline_L1_fu_580_ap_idle;
wire    grp_MLP_Pipeline_L1_fu_580_ap_ready;
wire   [6:0] grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_address0;
wire    grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_ce0;
wire    grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_we0;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_d0;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_opcode;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din1;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_din0;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_din0;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din1;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_opcode;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din1;
wire    grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_ce;
wire    grp_MLP_Pipeline_L1_L21_fu_779_ap_start;
wire    grp_MLP_Pipeline_L1_L21_fu_779_ap_done;
wire    grp_MLP_Pipeline_L1_L21_fu_779_ap_idle;
wire    grp_MLP_Pipeline_L1_L21_fu_779_ap_ready;
wire   [6:0] grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_address0;
wire    grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_ce0;
wire   [3:0] grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_address0;
wire    grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_ce0;
wire    grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_we0;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_d0;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_opcode;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din1;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_din0;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_din0;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_ce;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din0;
wire   [31:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din1;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din1;
wire   [1:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_opcode;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_ce;
wire   [63:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din0;
wire   [63:0] grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din1;
wire    grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_ce;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_done;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_idle;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_ready;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TREADY;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_address0;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_ce0;
wire   [31:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDATA;
wire    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TKEEP;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TSTRB;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TUSER;
wire   [0:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TLAST;
wire   [4:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TID;
wire   [4:0] grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDEST;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_done;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_idle;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_ready;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address0;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce0;
wire   [3:0] grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address1;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce1;
wire   [7:0] grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out;
wire    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out_ap_vld;
reg    grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg;
reg   [13:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_MLP_Pipeline_L1_fu_580_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg;
wire    ap_NS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [7:0] result_loc_fu_216;
wire    ap_CS_fsm_state14;
wire   [31:0] grp_fu_1655_p2;
reg   [31:0] grp_fu_1655_p0;
reg   [31:0] grp_fu_1655_p1;
reg    grp_fu_1655_ce;
wire   [31:0] grp_fu_1659_p2;
reg   [31:0] grp_fu_1659_p0;
reg   [31:0] grp_fu_1659_p1;
reg    grp_fu_1659_ce;
wire   [31:0] grp_fu_1663_p1;
reg   [63:0] grp_fu_1663_p0;
reg    grp_fu_1663_ce;
wire   [63:0] grp_fu_1666_p1;
reg   [31:0] grp_fu_1666_p0;
reg    grp_fu_1666_ce;
wire   [31:0] grp_fu_1669_p2;
reg   [31:0] grp_fu_1669_p0;
reg   [31:0] grp_fu_1669_p1;
reg    grp_fu_1669_ce;
wire   [63:0] grp_fu_1673_p2;
reg   [63:0] grp_fu_1673_p0;
reg   [63:0] grp_fu_1673_p1;
reg    grp_fu_1673_ce;
wire   [63:0] grp_fu_1677_p2;
reg   [63:0] grp_fu_1677_p0;
reg   [63:0] grp_fu_1677_p1;
reg    grp_fu_1677_ce;
wire    regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_INPUT_STREAM_V_data_V_U_apdone_blk;
wire   [31:0] INPUT_STREAM_TDATA_int_regslice;
wire    INPUT_STREAM_TVALID_int_regslice;
reg    INPUT_STREAM_TREADY_int_regslice;
wire    regslice_both_INPUT_STREAM_V_data_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_keep_V_U_apdone_blk;
wire   [3:0] INPUT_STREAM_TKEEP_int_regslice;
wire    regslice_both_INPUT_STREAM_V_keep_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_keep_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_strb_V_U_apdone_blk;
wire   [3:0] INPUT_STREAM_TSTRB_int_regslice;
wire    regslice_both_INPUT_STREAM_V_strb_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_strb_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_user_V_U_apdone_blk;
wire   [3:0] INPUT_STREAM_TUSER_int_regslice;
wire    regslice_both_INPUT_STREAM_V_user_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_user_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_last_V_U_apdone_blk;
wire   [0:0] INPUT_STREAM_TLAST_int_regslice;
wire    regslice_both_INPUT_STREAM_V_last_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_last_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_id_V_U_apdone_blk;
wire   [4:0] INPUT_STREAM_TID_int_regslice;
wire    regslice_both_INPUT_STREAM_V_id_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_id_V_U_ack_in;
wire    regslice_both_INPUT_STREAM_V_dest_V_U_apdone_blk;
wire   [4:0] INPUT_STREAM_TDEST_int_regslice;
wire    regslice_both_INPUT_STREAM_V_dest_V_U_vld_out;
wire    regslice_both_INPUT_STREAM_V_dest_V_U_ack_in;
wire    OUTPUT_STREAM_TVALID_int_regslice;
wire    OUTPUT_STREAM_TREADY_int_regslice;
wire    regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_user_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_user_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_user_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_id_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_id_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_id_V_U_vld_out;
wire    regslice_both_OUTPUT_STREAM_V_dest_V_U_apdone_blk;
wire    regslice_both_OUTPUT_STREAM_V_dest_V_U_ack_in_dummy;
wire    regslice_both_OUTPUT_STREAM_V_dest_V_U_vld_out;
wire    ap_ce_reg;
wire   [7:0] ap_return;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg = 1'b0;
#0 grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg = 1'b0;
#0 grp_MLP_Pipeline_L1_fu_580_ap_start_reg = 1'b0;
#0 grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg = 1'b0;
#0 grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg = 1'b0;
#0 grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg = 1'b0;
end

MLP_image_pixels_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
image_pixels_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(image_pixels_address0),
    .ce0(image_pixels_ce0),
    .we0(image_pixels_we0),
    .d0(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_d0),
    .q0(image_pixels_q0)
);

MLP_l_hidden2_outputs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
l_hidden2_outputs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(l_hidden2_outputs_address0),
    .ce0(l_hidden2_outputs_ce0),
    .we0(l_hidden2_outputs_we0),
    .d0(grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_d0),
    .q0(l_hidden2_outputs_q0)
);

MLP_l_out_outputs_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
l_out_outputs_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(l_out_outputs_address0),
    .ce0(l_out_outputs_ce0),
    .we0(l_out_outputs_we0),
    .d0(grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_d0),
    .q0(l_out_outputs_q0),
    .address1(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address1),
    .ce1(l_out_outputs_ce1),
    .q1(l_out_outputs_q1)
);

MLP_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2 grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start),
    .ap_done(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_done),
    .ap_idle(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_idle),
    .ap_ready(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_ready),
    .INPUT_STREAM_TVALID(INPUT_STREAM_TVALID_int_regslice),
    .INPUT_STREAM_TDATA(INPUT_STREAM_TDATA_int_regslice),
    .INPUT_STREAM_TREADY(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_INPUT_STREAM_TREADY),
    .INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP_int_regslice),
    .INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB_int_regslice),
    .INPUT_STREAM_TUSER(INPUT_STREAM_TUSER_int_regslice),
    .INPUT_STREAM_TLAST(INPUT_STREAM_TLAST_int_regslice),
    .INPUT_STREAM_TID(INPUT_STREAM_TID_int_regslice),
    .INPUT_STREAM_TDEST(INPUT_STREAM_TDEST_int_regslice),
    .image_pixels_address0(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_address0),
    .image_pixels_ce0(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_ce0),
    .image_pixels_we0(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_we0),
    .image_pixels_d0(grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_d0)
);

MLP_MLP_Pipeline_L1_L2 grp_MLP_Pipeline_L1_L2_fu_507(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_L1_L2_fu_507_ap_start),
    .ap_done(grp_MLP_Pipeline_L1_L2_fu_507_ap_done),
    .ap_idle(grp_MLP_Pipeline_L1_L2_fu_507_ap_idle),
    .ap_ready(grp_MLP_Pipeline_L1_L2_fu_507_ap_ready),
    .image_pixels_address0(grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_address0),
    .image_pixels_ce0(grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_ce0),
    .image_pixels_q0(image_pixels_q0),
    .p_out(grp_MLP_Pipeline_L1_L2_fu_507_p_out),
    .p_out_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out_ap_vld),
    .p_out1(grp_MLP_Pipeline_L1_L2_fu_507_p_out1),
    .p_out1_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out1_ap_vld),
    .p_out2(grp_MLP_Pipeline_L1_L2_fu_507_p_out2),
    .p_out2_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out2_ap_vld),
    .p_out3(grp_MLP_Pipeline_L1_L2_fu_507_p_out3),
    .p_out3_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out3_ap_vld),
    .p_out4(grp_MLP_Pipeline_L1_L2_fu_507_p_out4),
    .p_out4_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out4_ap_vld),
    .p_out5(grp_MLP_Pipeline_L1_L2_fu_507_p_out5),
    .p_out5_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out5_ap_vld),
    .p_out6(grp_MLP_Pipeline_L1_L2_fu_507_p_out6),
    .p_out6_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out6_ap_vld),
    .p_out7(grp_MLP_Pipeline_L1_L2_fu_507_p_out7),
    .p_out7_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out7_ap_vld),
    .p_out8(grp_MLP_Pipeline_L1_L2_fu_507_p_out8),
    .p_out8_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out8_ap_vld),
    .p_out9(grp_MLP_Pipeline_L1_L2_fu_507_p_out9),
    .p_out9_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out9_ap_vld),
    .p_out10(grp_MLP_Pipeline_L1_L2_fu_507_p_out10),
    .p_out10_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out10_ap_vld),
    .p_out11(grp_MLP_Pipeline_L1_L2_fu_507_p_out11),
    .p_out11_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out11_ap_vld),
    .p_out12(grp_MLP_Pipeline_L1_L2_fu_507_p_out12),
    .p_out12_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out12_ap_vld),
    .p_out13(grp_MLP_Pipeline_L1_L2_fu_507_p_out13),
    .p_out13_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out13_ap_vld),
    .p_out14(grp_MLP_Pipeline_L1_L2_fu_507_p_out14),
    .p_out14_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out14_ap_vld),
    .p_out15(grp_MLP_Pipeline_L1_L2_fu_507_p_out15),
    .p_out15_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out15_ap_vld),
    .p_out16(grp_MLP_Pipeline_L1_L2_fu_507_p_out16),
    .p_out16_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out16_ap_vld),
    .p_out17(grp_MLP_Pipeline_L1_L2_fu_507_p_out17),
    .p_out17_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out17_ap_vld),
    .p_out18(grp_MLP_Pipeline_L1_L2_fu_507_p_out18),
    .p_out18_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out18_ap_vld),
    .p_out19(grp_MLP_Pipeline_L1_L2_fu_507_p_out19),
    .p_out19_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out19_ap_vld),
    .p_out20(grp_MLP_Pipeline_L1_L2_fu_507_p_out20),
    .p_out20_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out20_ap_vld),
    .p_out21(grp_MLP_Pipeline_L1_L2_fu_507_p_out21),
    .p_out21_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out21_ap_vld),
    .p_out22(grp_MLP_Pipeline_L1_L2_fu_507_p_out22),
    .p_out22_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out22_ap_vld),
    .p_out23(grp_MLP_Pipeline_L1_L2_fu_507_p_out23),
    .p_out23_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out23_ap_vld),
    .p_out24(grp_MLP_Pipeline_L1_L2_fu_507_p_out24),
    .p_out24_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out24_ap_vld),
    .p_out25(grp_MLP_Pipeline_L1_L2_fu_507_p_out25),
    .p_out25_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out25_ap_vld),
    .p_out26(grp_MLP_Pipeline_L1_L2_fu_507_p_out26),
    .p_out26_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out26_ap_vld),
    .p_out27(grp_MLP_Pipeline_L1_L2_fu_507_p_out27),
    .p_out27_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out27_ap_vld),
    .p_out28(grp_MLP_Pipeline_L1_L2_fu_507_p_out28),
    .p_out28_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out28_ap_vld),
    .p_out29(grp_MLP_Pipeline_L1_L2_fu_507_p_out29),
    .p_out29_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out29_ap_vld),
    .p_out30(grp_MLP_Pipeline_L1_L2_fu_507_p_out30),
    .p_out30_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out30_ap_vld),
    .p_out31(grp_MLP_Pipeline_L1_L2_fu_507_p_out31),
    .p_out31_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out31_ap_vld),
    .p_out32(grp_MLP_Pipeline_L1_L2_fu_507_p_out32),
    .p_out32_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out32_ap_vld),
    .p_out33(grp_MLP_Pipeline_L1_L2_fu_507_p_out33),
    .p_out33_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out33_ap_vld),
    .p_out34(grp_MLP_Pipeline_L1_L2_fu_507_p_out34),
    .p_out34_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out34_ap_vld),
    .p_out35(grp_MLP_Pipeline_L1_L2_fu_507_p_out35),
    .p_out35_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out35_ap_vld),
    .p_out36(grp_MLP_Pipeline_L1_L2_fu_507_p_out36),
    .p_out36_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out36_ap_vld),
    .p_out37(grp_MLP_Pipeline_L1_L2_fu_507_p_out37),
    .p_out37_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out37_ap_vld),
    .p_out38(grp_MLP_Pipeline_L1_L2_fu_507_p_out38),
    .p_out38_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out38_ap_vld),
    .p_out39(grp_MLP_Pipeline_L1_L2_fu_507_p_out39),
    .p_out39_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out39_ap_vld),
    .p_out40(grp_MLP_Pipeline_L1_L2_fu_507_p_out40),
    .p_out40_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out40_ap_vld),
    .p_out41(grp_MLP_Pipeline_L1_L2_fu_507_p_out41),
    .p_out41_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out41_ap_vld),
    .p_out42(grp_MLP_Pipeline_L1_L2_fu_507_p_out42),
    .p_out42_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out42_ap_vld),
    .p_out43(grp_MLP_Pipeline_L1_L2_fu_507_p_out43),
    .p_out43_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out43_ap_vld),
    .p_out44(grp_MLP_Pipeline_L1_L2_fu_507_p_out44),
    .p_out44_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out44_ap_vld),
    .p_out45(grp_MLP_Pipeline_L1_L2_fu_507_p_out45),
    .p_out45_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out45_ap_vld),
    .p_out46(grp_MLP_Pipeline_L1_L2_fu_507_p_out46),
    .p_out46_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out46_ap_vld),
    .p_out47(grp_MLP_Pipeline_L1_L2_fu_507_p_out47),
    .p_out47_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out47_ap_vld),
    .p_out48(grp_MLP_Pipeline_L1_L2_fu_507_p_out48),
    .p_out48_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out48_ap_vld),
    .p_out49(grp_MLP_Pipeline_L1_L2_fu_507_p_out49),
    .p_out49_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out49_ap_vld),
    .p_out50(grp_MLP_Pipeline_L1_L2_fu_507_p_out50),
    .p_out50_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out50_ap_vld),
    .p_out51(grp_MLP_Pipeline_L1_L2_fu_507_p_out51),
    .p_out51_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out51_ap_vld),
    .p_out52(grp_MLP_Pipeline_L1_L2_fu_507_p_out52),
    .p_out52_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out52_ap_vld),
    .p_out53(grp_MLP_Pipeline_L1_L2_fu_507_p_out53),
    .p_out53_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out53_ap_vld),
    .p_out54(grp_MLP_Pipeline_L1_L2_fu_507_p_out54),
    .p_out54_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out54_ap_vld),
    .p_out55(grp_MLP_Pipeline_L1_L2_fu_507_p_out55),
    .p_out55_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out55_ap_vld),
    .p_out56(grp_MLP_Pipeline_L1_L2_fu_507_p_out56),
    .p_out56_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out56_ap_vld),
    .p_out57(grp_MLP_Pipeline_L1_L2_fu_507_p_out57),
    .p_out57_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out57_ap_vld),
    .p_out58(grp_MLP_Pipeline_L1_L2_fu_507_p_out58),
    .p_out58_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out58_ap_vld),
    .p_out59(grp_MLP_Pipeline_L1_L2_fu_507_p_out59),
    .p_out59_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out59_ap_vld),
    .p_out60(grp_MLP_Pipeline_L1_L2_fu_507_p_out60),
    .p_out60_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out60_ap_vld),
    .p_out61(grp_MLP_Pipeline_L1_L2_fu_507_p_out61),
    .p_out61_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out61_ap_vld),
    .p_out62(grp_MLP_Pipeline_L1_L2_fu_507_p_out62),
    .p_out62_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out62_ap_vld),
    .p_out63(grp_MLP_Pipeline_L1_L2_fu_507_p_out63),
    .p_out63_ap_vld(grp_MLP_Pipeline_L1_L2_fu_507_p_out63_ap_vld),
    .grp_fu_1655_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din0),
    .grp_fu_1655_p_din1(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din1),
    .grp_fu_1655_p_opcode(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_opcode),
    .grp_fu_1655_p_dout0(grp_fu_1655_p2),
    .grp_fu_1655_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_ce),
    .grp_fu_1659_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din0),
    .grp_fu_1659_p_din1(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din1),
    .grp_fu_1659_p_dout0(grp_fu_1659_p2),
    .grp_fu_1659_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_ce),
    .grp_fu_1663_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_din0),
    .grp_fu_1663_p_dout0(grp_fu_1663_p1),
    .grp_fu_1663_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_ce),
    .grp_fu_1666_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_din0),
    .grp_fu_1666_p_dout0(grp_fu_1666_p1),
    .grp_fu_1666_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_ce),
    .grp_fu_1669_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din0),
    .grp_fu_1669_p_din1(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din1),
    .grp_fu_1669_p_dout0(grp_fu_1669_p2),
    .grp_fu_1669_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_ce),
    .grp_fu_1673_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din0),
    .grp_fu_1673_p_din1(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din1),
    .grp_fu_1673_p_opcode(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_opcode),
    .grp_fu_1673_p_dout0(grp_fu_1673_p2),
    .grp_fu_1673_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_ce),
    .grp_fu_1677_p_din0(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din0),
    .grp_fu_1677_p_din1(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din1),
    .grp_fu_1677_p_dout0(grp_fu_1677_p2),
    .grp_fu_1677_p_ce(grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_ce)
);

MLP_MLP_Pipeline_L1 grp_MLP_Pipeline_L1_fu_580(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_L1_fu_580_ap_start),
    .ap_done(grp_MLP_Pipeline_L1_fu_580_ap_done),
    .ap_idle(grp_MLP_Pipeline_L1_fu_580_ap_idle),
    .ap_ready(grp_MLP_Pipeline_L1_fu_580_ap_ready),
    .p_reload410(grp_MLP_Pipeline_L1_L2_fu_507_p_out63),
    .p_reload409(grp_MLP_Pipeline_L1_L2_fu_507_p_out62),
    .p_reload408(grp_MLP_Pipeline_L1_L2_fu_507_p_out61),
    .p_reload407(grp_MLP_Pipeline_L1_L2_fu_507_p_out60),
    .p_reload406(grp_MLP_Pipeline_L1_L2_fu_507_p_out59),
    .p_reload405(grp_MLP_Pipeline_L1_L2_fu_507_p_out58),
    .p_reload404(grp_MLP_Pipeline_L1_L2_fu_507_p_out57),
    .p_reload403(grp_MLP_Pipeline_L1_L2_fu_507_p_out56),
    .p_reload402(grp_MLP_Pipeline_L1_L2_fu_507_p_out55),
    .p_reload401(grp_MLP_Pipeline_L1_L2_fu_507_p_out54),
    .p_reload400(grp_MLP_Pipeline_L1_L2_fu_507_p_out53),
    .p_reload399(grp_MLP_Pipeline_L1_L2_fu_507_p_out52),
    .p_reload398(grp_MLP_Pipeline_L1_L2_fu_507_p_out51),
    .p_reload397(grp_MLP_Pipeline_L1_L2_fu_507_p_out50),
    .p_reload396(grp_MLP_Pipeline_L1_L2_fu_507_p_out49),
    .p_reload395(grp_MLP_Pipeline_L1_L2_fu_507_p_out48),
    .p_reload394(grp_MLP_Pipeline_L1_L2_fu_507_p_out47),
    .p_reload393(grp_MLP_Pipeline_L1_L2_fu_507_p_out46),
    .p_reload392(grp_MLP_Pipeline_L1_L2_fu_507_p_out45),
    .p_reload391(grp_MLP_Pipeline_L1_L2_fu_507_p_out44),
    .p_reload390(grp_MLP_Pipeline_L1_L2_fu_507_p_out43),
    .p_reload389(grp_MLP_Pipeline_L1_L2_fu_507_p_out42),
    .p_reload388(grp_MLP_Pipeline_L1_L2_fu_507_p_out41),
    .p_reload387(grp_MLP_Pipeline_L1_L2_fu_507_p_out40),
    .p_reload386(grp_MLP_Pipeline_L1_L2_fu_507_p_out39),
    .p_reload385(grp_MLP_Pipeline_L1_L2_fu_507_p_out38),
    .p_reload384(grp_MLP_Pipeline_L1_L2_fu_507_p_out37),
    .p_reload383(grp_MLP_Pipeline_L1_L2_fu_507_p_out36),
    .p_reload382(grp_MLP_Pipeline_L1_L2_fu_507_p_out35),
    .p_reload381(grp_MLP_Pipeline_L1_L2_fu_507_p_out34),
    .p_reload380(grp_MLP_Pipeline_L1_L2_fu_507_p_out33),
    .p_reload379(grp_MLP_Pipeline_L1_L2_fu_507_p_out32),
    .p_reload378(grp_MLP_Pipeline_L1_L2_fu_507_p_out31),
    .p_reload377(grp_MLP_Pipeline_L1_L2_fu_507_p_out30),
    .p_reload376(grp_MLP_Pipeline_L1_L2_fu_507_p_out29),
    .p_reload375(grp_MLP_Pipeline_L1_L2_fu_507_p_out28),
    .p_reload374(grp_MLP_Pipeline_L1_L2_fu_507_p_out27),
    .p_reload373(grp_MLP_Pipeline_L1_L2_fu_507_p_out26),
    .p_reload372(grp_MLP_Pipeline_L1_L2_fu_507_p_out25),
    .p_reload371(grp_MLP_Pipeline_L1_L2_fu_507_p_out24),
    .p_reload370(grp_MLP_Pipeline_L1_L2_fu_507_p_out23),
    .p_reload369(grp_MLP_Pipeline_L1_L2_fu_507_p_out22),
    .p_reload368(grp_MLP_Pipeline_L1_L2_fu_507_p_out21),
    .p_reload367(grp_MLP_Pipeline_L1_L2_fu_507_p_out20),
    .p_reload366(grp_MLP_Pipeline_L1_L2_fu_507_p_out19),
    .p_reload365(grp_MLP_Pipeline_L1_L2_fu_507_p_out18),
    .p_reload364(grp_MLP_Pipeline_L1_L2_fu_507_p_out17),
    .p_reload363(grp_MLP_Pipeline_L1_L2_fu_507_p_out16),
    .p_reload362(grp_MLP_Pipeline_L1_L2_fu_507_p_out15),
    .p_reload361(grp_MLP_Pipeline_L1_L2_fu_507_p_out14),
    .p_reload360(grp_MLP_Pipeline_L1_L2_fu_507_p_out13),
    .p_reload359(grp_MLP_Pipeline_L1_L2_fu_507_p_out12),
    .p_reload358(grp_MLP_Pipeline_L1_L2_fu_507_p_out11),
    .p_reload357(grp_MLP_Pipeline_L1_L2_fu_507_p_out10),
    .p_reload356(grp_MLP_Pipeline_L1_L2_fu_507_p_out9),
    .p_reload355(grp_MLP_Pipeline_L1_L2_fu_507_p_out8),
    .p_reload354(grp_MLP_Pipeline_L1_L2_fu_507_p_out7),
    .p_reload353(grp_MLP_Pipeline_L1_L2_fu_507_p_out6),
    .p_reload352(grp_MLP_Pipeline_L1_L2_fu_507_p_out5),
    .p_reload351(grp_MLP_Pipeline_L1_L2_fu_507_p_out4),
    .p_reload350(grp_MLP_Pipeline_L1_L2_fu_507_p_out3),
    .p_reload349(grp_MLP_Pipeline_L1_L2_fu_507_p_out2),
    .p_reload348(grp_MLP_Pipeline_L1_L2_fu_507_p_out1),
    .p_reload(grp_MLP_Pipeline_L1_L2_fu_507_p_out),
    .l_hidden2_outputs_address0(grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_address0),
    .l_hidden2_outputs_ce0(grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_ce0),
    .l_hidden2_outputs_we0(grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_we0),
    .l_hidden2_outputs_d0(grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_d0),
    .grp_fu_1655_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din0),
    .grp_fu_1655_p_din1(grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din1),
    .grp_fu_1655_p_opcode(grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_opcode),
    .grp_fu_1655_p_dout0(grp_fu_1655_p2),
    .grp_fu_1655_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_ce),
    .grp_fu_1659_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din0),
    .grp_fu_1659_p_din1(grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din1),
    .grp_fu_1659_p_dout0(grp_fu_1659_p2),
    .grp_fu_1659_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_ce),
    .grp_fu_1663_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_din0),
    .grp_fu_1663_p_dout0(grp_fu_1663_p1),
    .grp_fu_1663_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_ce),
    .grp_fu_1666_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_din0),
    .grp_fu_1666_p_dout0(grp_fu_1666_p1),
    .grp_fu_1666_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_ce),
    .grp_fu_1669_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din0),
    .grp_fu_1669_p_din1(grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din1),
    .grp_fu_1669_p_dout0(grp_fu_1669_p2),
    .grp_fu_1669_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_ce),
    .grp_fu_1673_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din0),
    .grp_fu_1673_p_din1(grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din1),
    .grp_fu_1673_p_opcode(grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_opcode),
    .grp_fu_1673_p_dout0(grp_fu_1673_p2),
    .grp_fu_1673_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_ce),
    .grp_fu_1677_p_din0(grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din0),
    .grp_fu_1677_p_din1(grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din1),
    .grp_fu_1677_p_dout0(grp_fu_1677_p2),
    .grp_fu_1677_p_ce(grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_ce)
);

MLP_MLP_Pipeline_L1_L21 grp_MLP_Pipeline_L1_L21_fu_779(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_L1_L21_fu_779_ap_start),
    .ap_done(grp_MLP_Pipeline_L1_L21_fu_779_ap_done),
    .ap_idle(grp_MLP_Pipeline_L1_L21_fu_779_ap_idle),
    .ap_ready(grp_MLP_Pipeline_L1_L21_fu_779_ap_ready),
    .l_hidden2_outputs_address0(grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_address0),
    .l_hidden2_outputs_ce0(grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_ce0),
    .l_hidden2_outputs_q0(l_hidden2_outputs_q0),
    .l_out_outputs_address0(grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_address0),
    .l_out_outputs_ce0(grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_ce0),
    .l_out_outputs_we0(grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_we0),
    .l_out_outputs_d0(grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_d0),
    .grp_fu_1655_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din0),
    .grp_fu_1655_p_din1(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din1),
    .grp_fu_1655_p_opcode(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_opcode),
    .grp_fu_1655_p_dout0(grp_fu_1655_p2),
    .grp_fu_1655_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_ce),
    .grp_fu_1659_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din0),
    .grp_fu_1659_p_din1(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din1),
    .grp_fu_1659_p_dout0(grp_fu_1659_p2),
    .grp_fu_1659_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_ce),
    .grp_fu_1663_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_din0),
    .grp_fu_1663_p_dout0(grp_fu_1663_p1),
    .grp_fu_1663_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_ce),
    .grp_fu_1666_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_din0),
    .grp_fu_1666_p_dout0(grp_fu_1666_p1),
    .grp_fu_1666_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_ce),
    .grp_fu_1669_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din0),
    .grp_fu_1669_p_din1(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din1),
    .grp_fu_1669_p_dout0(grp_fu_1669_p2),
    .grp_fu_1669_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_ce),
    .grp_fu_1673_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din0),
    .grp_fu_1673_p_din1(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din1),
    .grp_fu_1673_p_opcode(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_opcode),
    .grp_fu_1673_p_dout0(grp_fu_1673_p2),
    .grp_fu_1673_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_ce),
    .grp_fu_1677_p_din0(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din0),
    .grp_fu_1677_p_din1(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din1),
    .grp_fu_1677_p_dout0(grp_fu_1677_p2),
    .grp_fu_1677_p_ce(grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_ce)
);

MLP_MLP_Pipeline_VITIS_LOOP_98_4 grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start),
    .ap_done(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_done),
    .ap_idle(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_idle),
    .ap_ready(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_ready),
    .OUTPUT_STREAM_TREADY(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TREADY),
    .l_out_outputs_address0(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_address0),
    .l_out_outputs_ce0(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_ce0),
    .l_out_outputs_q0(l_out_outputs_q0),
    .OUTPUT_STREAM_TDATA(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDATA),
    .OUTPUT_STREAM_TVALID(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .OUTPUT_STREAM_TKEEP(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TKEEP),
    .OUTPUT_STREAM_TSTRB(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TSTRB),
    .OUTPUT_STREAM_TUSER(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TUSER),
    .OUTPUT_STREAM_TLAST(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TLAST),
    .OUTPUT_STREAM_TID(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TID),
    .OUTPUT_STREAM_TDEST(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDEST)
);

MLP_MLP_Pipeline_VITIS_LOOP_23_1 grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start),
    .ap_done(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_done),
    .ap_idle(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_idle),
    .ap_ready(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_ready),
    .l_out_outputs_address0(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address0),
    .l_out_outputs_ce0(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce0),
    .l_out_outputs_q0(l_out_outputs_q0),
    .l_out_outputs_address1(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address1),
    .l_out_outputs_ce1(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce1),
    .l_out_outputs_q1(l_out_outputs_q1),
    .result_out(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out),
    .result_out_ap_vld(grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out_ap_vld)
);

MLP_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(result_loc_fu_216)
);

MLP_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U372(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1655_p0),
    .din1(grp_fu_1655_p1),
    .ce(grp_fu_1655_ce),
    .dout(grp_fu_1655_p2)
);

MLP_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U373(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1659_p0),
    .din1(grp_fu_1659_p1),
    .ce(grp_fu_1659_ce),
    .dout(grp_fu_1659_p2)
);

MLP_fptrunc_64ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_2_no_dsp_1_U374(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1663_p0),
    .ce(grp_fu_1663_ce),
    .dout(grp_fu_1663_p1)
);

MLP_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U375(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1666_p0),
    .ce(grp_fu_1666_ce),
    .dout(grp_fu_1666_p1)
);

MLP_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_8_full_dsp_1_U376(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1669_p0),
    .din1(grp_fu_1669_p1),
    .ce(grp_fu_1669_ce),
    .dout(grp_fu_1669_p2)
);

MLP_dadd_64ns_64ns_64_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_5_full_dsp_1_U377(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1673_p0),
    .din1(grp_fu_1673_p1),
    .ce(grp_fu_1673_ce),
    .dout(grp_fu_1673_p2)
);

MLP_ddiv_64ns_64ns_64_22_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 22 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_22_no_dsp_1_U378(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_1677_p0),
    .din1(grp_fu_1677_p1),
    .ce(grp_fu_1677_ce),
    .dout(grp_fu_1677_p2)
);

MLP_regslice_both #(
    .DataWidth( 32 ))
regslice_both_INPUT_STREAM_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TDATA),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_data_V_U_ack_in),
    .data_out(INPUT_STREAM_TDATA_int_regslice),
    .vld_out(INPUT_STREAM_TVALID_int_regslice),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_data_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_INPUT_STREAM_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TKEEP),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_keep_V_U_ack_in),
    .data_out(INPUT_STREAM_TKEEP_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_keep_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_keep_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_INPUT_STREAM_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TSTRB),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_strb_V_U_ack_in),
    .data_out(INPUT_STREAM_TSTRB_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_strb_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_strb_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_INPUT_STREAM_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TUSER),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_user_V_U_ack_in),
    .data_out(INPUT_STREAM_TUSER_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_user_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_user_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 1 ))
regslice_both_INPUT_STREAM_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TLAST),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_last_V_U_ack_in),
    .data_out(INPUT_STREAM_TLAST_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_last_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_last_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 5 ))
regslice_both_INPUT_STREAM_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TID),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_id_V_U_ack_in),
    .data_out(INPUT_STREAM_TID_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_id_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_id_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 5 ))
regslice_both_INPUT_STREAM_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(INPUT_STREAM_TDEST),
    .vld_in(INPUT_STREAM_TVALID),
    .ack_in(regslice_both_INPUT_STREAM_V_dest_V_U_ack_in),
    .data_out(INPUT_STREAM_TDEST_int_regslice),
    .vld_out(regslice_both_INPUT_STREAM_V_dest_V_U_vld_out),
    .ack_out(INPUT_STREAM_TREADY_int_regslice),
    .apdone_blk(regslice_both_INPUT_STREAM_V_dest_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 32 ))
regslice_both_OUTPUT_STREAM_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDATA),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(OUTPUT_STREAM_TREADY_int_regslice),
    .data_out(OUTPUT_STREAM_TDATA),
    .vld_out(regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_OUTPUT_STREAM_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TKEEP),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_keep_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TKEEP),
    .vld_out(regslice_both_OUTPUT_STREAM_V_keep_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_keep_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_OUTPUT_STREAM_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TSTRB),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_strb_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TSTRB),
    .vld_out(regslice_both_OUTPUT_STREAM_V_strb_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_strb_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 4 ))
regslice_both_OUTPUT_STREAM_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TUSER),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_user_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TUSER),
    .vld_out(regslice_both_OUTPUT_STREAM_V_user_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_user_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 1 ))
regslice_both_OUTPUT_STREAM_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TLAST),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_last_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TLAST),
    .vld_out(regslice_both_OUTPUT_STREAM_V_last_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_last_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 5 ))
regslice_both_OUTPUT_STREAM_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TID),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_id_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TID),
    .vld_out(regslice_both_OUTPUT_STREAM_V_id_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_id_V_U_apdone_blk)
);

MLP_regslice_both #(
    .DataWidth( 5 ))
regslice_both_OUTPUT_STREAM_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TDEST),
    .vld_in(grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID),
    .ack_in(regslice_both_OUTPUT_STREAM_V_dest_V_U_ack_in_dummy),
    .data_out(OUTPUT_STREAM_TDEST),
    .vld_out(regslice_both_OUTPUT_STREAM_V_dest_V_U_vld_out),
    .ack_out(OUTPUT_STREAM_TREADY),
    .apdone_blk(regslice_both_OUTPUT_STREAM_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_L1_L21_fu_779_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_L1_L2_fu_507_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_L1_fu_580_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_MLP_Pipeline_L1_fu_580_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_L1_fu_580_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_L1_fu_580_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state12) & (1'b1 == ap_CS_fsm_state11))) begin
            grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg <= 1'b1;
        end else if ((grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_ready == 1'b1)) begin
            grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        result_loc_fu_216 <= grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_result_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        INPUT_STREAM_TREADY_int_regslice = grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_INPUT_STREAM_TREADY;
    end else begin
        INPUT_STREAM_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_L1_L2_fu_507_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_L1_fu_580_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_MLP_Pipeline_L1_L21_fu_779_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1655_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1655_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1655_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_ce;
    end else begin
        grp_fu_1655_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1655_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1655_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1655_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din0;
    end else begin
        grp_fu_1655_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1655_p1 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1655_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1655_p1 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1655_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1655_p1 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1655_p_din1;
    end else begin
        grp_fu_1655_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1659_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1659_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1659_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_ce;
    end else begin
        grp_fu_1659_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1659_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1659_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1659_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din0;
    end else begin
        grp_fu_1659_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1659_p1 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1659_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1659_p1 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1659_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1659_p1 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1659_p_din1;
    end else begin
        grp_fu_1659_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1663_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1663_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1663_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_ce;
    end else begin
        grp_fu_1663_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1663_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1663_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1663_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1663_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1663_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1663_p_din0;
    end else begin
        grp_fu_1663_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1666_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1666_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1666_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_ce;
    end else begin
        grp_fu_1666_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1666_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1666_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1666_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1666_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1666_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1666_p_din0;
    end else begin
        grp_fu_1666_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1669_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1669_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1669_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_ce;
    end else begin
        grp_fu_1669_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1669_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1669_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1669_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din0;
    end else begin
        grp_fu_1669_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1669_p1 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1669_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1669_p1 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1669_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1669_p1 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1669_p_din1;
    end else begin
        grp_fu_1669_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1673_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1673_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1673_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_ce;
    end else begin
        grp_fu_1673_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1673_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1673_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1673_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din0;
    end else begin
        grp_fu_1673_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1673_p1 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1673_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1673_p1 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1673_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1673_p1 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1673_p_din1;
    end else begin
        grp_fu_1673_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1677_ce = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1677_ce = grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1677_ce = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_ce;
    end else begin
        grp_fu_1677_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1677_p0 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1677_p0 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1677_p0 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din0;
    end else begin
        grp_fu_1677_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_1677_p1 = grp_MLP_Pipeline_L1_L21_fu_779_grp_fu_1677_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_1677_p1 = grp_MLP_Pipeline_L1_fu_580_grp_fu_1677_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_1677_p1 = grp_MLP_Pipeline_L1_L2_fu_507_grp_fu_1677_p_din1;
    end else begin
        grp_fu_1677_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        image_pixels_address0 = grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        image_pixels_address0 = grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_address0;
    end else begin
        image_pixels_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        image_pixels_ce0 = grp_MLP_Pipeline_L1_L2_fu_507_image_pixels_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        image_pixels_ce0 = grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_ce0;
    end else begin
        image_pixels_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        image_pixels_we0 = grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_image_pixels_we0;
    end else begin
        image_pixels_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        l_hidden2_outputs_address0 = grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        l_hidden2_outputs_address0 = grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_address0;
    end else begin
        l_hidden2_outputs_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        l_hidden2_outputs_ce0 = grp_MLP_Pipeline_L1_L21_fu_779_l_hidden2_outputs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        l_hidden2_outputs_ce0 = grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_ce0;
    end else begin
        l_hidden2_outputs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        l_hidden2_outputs_we0 = grp_MLP_Pipeline_L1_fu_580_l_hidden2_outputs_we0;
    end else begin
        l_hidden2_outputs_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        l_out_outputs_address0 = grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        l_out_outputs_address0 = grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        l_out_outputs_address0 = grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_address0;
    end else begin
        l_out_outputs_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        l_out_outputs_ce0 = grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        l_out_outputs_ce0 = grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_l_out_outputs_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        l_out_outputs_ce0 = grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_ce0;
    end else begin
        l_out_outputs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        l_out_outputs_ce1 = grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_l_out_outputs_ce1;
    end else begin
        l_out_outputs_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        l_out_outputs_we0 = grp_MLP_Pipeline_L1_L21_fu_779_l_out_outputs_we0;
    end else begin
        l_out_outputs_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_MLP_Pipeline_L1_L2_fu_507_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_MLP_Pipeline_L1_fu_580_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_MLP_Pipeline_L1_L21_fu_779_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_OUTPUT_STREAM_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign INPUT_STREAM_TREADY = regslice_both_INPUT_STREAM_V_data_V_U_ack_in;

assign OUTPUT_STREAM_TVALID = regslice_both_OUTPUT_STREAM_V_data_V_U_vld_out;

assign OUTPUT_STREAM_TVALID_int_regslice = grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TVALID;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state12 = ap_NS_fsm[32'd11];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_MLP_Pipeline_L1_L21_fu_779_ap_start = grp_MLP_Pipeline_L1_L21_fu_779_ap_start_reg;

assign grp_MLP_Pipeline_L1_L2_fu_507_ap_start = grp_MLP_Pipeline_L1_L2_fu_507_ap_start_reg;

assign grp_MLP_Pipeline_L1_fu_580_ap_start = grp_MLP_Pipeline_L1_fu_580_ap_start_reg;

assign grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start = grp_MLP_Pipeline_VITIS_LOOP_23_1_fu_808_ap_start_reg;

assign grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start = grp_MLP_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_83_2_fu_488_ap_start_reg;

assign grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_OUTPUT_STREAM_TREADY = (ap_CS_fsm_state11 & OUTPUT_STREAM_TREADY_int_regslice);

assign grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start = grp_MLP_Pipeline_VITIS_LOOP_98_4_fu_789_ap_start_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "MLP_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //MLP

